### ISSUE TITLE
Commands hang on ghcup installation prompts when not already installed

### ISSUE THREAD

**Issue by jeremyjh** [sestrella/asdf-ghcup#10]
On MacOS I used this to try to install ghc and it would just hang, and only after I hit ctrl-c I could see prompts from ghcup. I just installed ghcup from the website and then this package worked fine.

**Comment by sestrella** [comment]
@jeremyjh A closer look revealed a location that might potentially cause this behavior: it appears that the GHCup installation script has a [few spots](https://github.com/haskell/ghcup-hs/blob/master/scripts/bootstrap/bootstrap-haskell#L780-L789) where the user must interact. Fortunately, it appears that the installation script can be made to be non-interactive.  I merged a PR #12 that made some adjustments to the GHCup installation script. Would you mind giving this a try?

**Comment by sestrella** [comment]
I'm closing this one because it was already addressed by https://github.com/sestrella/asdf-ghcup/pull/12
